// <auto-generated />
using BlogAppWASM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogAppWASM.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20241029101250_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BlogAppWASM.Shared.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Lorum Ipsum Sit etc",
                            Title = "Introduction to Blazor"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Lorum Ipsum Sit etc",
                            Title = "State Management in Blazor"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Lorum Ipsum Sit etc",
                            Title = "Building a Blog with Blazor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
